export default `
<a href="https://letterboxd.com/roncers/film/stagecoach/2/#comments">Link to the spanish version / Enlace versión en español</a>

<blockquote>"Well, they're saved from the blessings of civilization." – Doc Boone</blockquote>

I have seen few movies in my life that have a pace remotely similar to this gem. Not content with this, it is the first <i>road movie</i> (well made) in history. And if that wasn't enough, Orson Welles watched it over 40 times to make <i>Citizen Kane</i>. When asked in an interview in '67 about the directors he admired, he mentioned above ALL the "old masters," meaning by this: John Ford, John Ford, and John Ford.

Released in 1939. The 30s in the United States were marked by the Great Depression (triggered by the crash of '29), the Dust Bowl disaster (sad farmers), the end of Prohibition in '33, tension over the approach of World War II, and several strong hurricanes that battered Florida and New England. Being a period of such poverty and instability, there was great political discontent regarding how the crisis was handled, as well as with the banks and the Stock Market. Several unions were created seeking to fight for workers' rights. Due to the consequences of the Dust Bowl, hundreds of farmers from the Southwest were forced to move to California to find work, undertaking a journey similar to the one the film’s protagonists undergo, wherein, instead of facing Indians, they faced people's prejudices—which, on occasion, can be worse than the arrows of the natives.

First of all, I’m going to give a brief summary of what happens; if you’ve just watched it and don’t want to review it, skip to the line of dashes (-).

It is set in the 1880s in Tonto, a small town in Arizona, USA. 8 motley travelers find themselves thrown into a varied journey that will mark the vestiges of their lives. All are heading to Lordsburg, New Mexico, each for different reasons:

- Lucy Mallory: A pregnant woman in search of her soldier husband;
- Hatfield: A gambler, war veteran, who upon seeing Lucy joins the crossing like a moth to a flame;
- Gatewood: A banker fleeing town, stealing a recently received deposit and abandoning his wife;
- Curly Wilcox: The marshal who travels, in part, to watch over the passengers' safety against an Apache threat on the trip, and also to find Ringo Kid and collect his reward—speaking of whom;
- Ringo Kid: A fugitive from justice looking for the men who killed his family and put him in jail;
- Dallas: A prostitute banished from her town by the Law and Order League, an organization formed after the Civil War to watch over "correct moral values" <a href="https://www.newyorkalmanack.com/2021/10/saratoga-countys-law-and-order-league/"> (more info here, for the curious) </a>;
- Buck: The cowardly but friendly stagecoach driver;
- Peacock: A traveling liquor salesman whom everyone mistakes for a pastor and, to top it off;
- Josiah Boone: The nihilistic doctor, also expelled from town, in this case, for his debts and bad reputation.

As I mentioned, they are a very diverse group, so under normal conditions, most of these individuals wouldn't interact with each other. But this is not the case. As I said, it’s the 1880s and the only way they have to transport themselves is a claustrophobic apparatus called a stagecoach.
What a hassle!
Not only do we observe how much the world has changed regarding transport, but you can feel why it has changed so much. Even though we are destined to live this life and the only thing we can choose is the kindness with which we treat those around us, sometimes, out of pure selfishness or inertia, we aren't conscious that other people are just like us.

I’m going to go straight to the end of the plot, without dwelling on the intermediate vicissitudes:

- Lucy: With a child and reunited with her husband;
- Hatfield: Dead at the hands of the Apaches;
- Gatewood: Imprisoned for his misdeed;
- Curly Wilcox: Frees Ringo from the law, renouncing the reward for capturing him;
- Ringo Kid and Dallas: Flee civilization together;
- Buck: Ends the shootout wounded but safe and sound;
- Peacock: Returns home with a great story to tell his family;
- Josiah Boone: As for motives, he is the only one who starts the same as he ends; he learns nothing, because he already knows what’s what. Perhaps he gains a story and does the only thing he knows is right: helping others, because he cannot help himself. What an irony that the most cynical character is the doctor who helps cure people. The movie is full of these satires; it's one of the reasons I like it so much.

---

With the passage of time, transport has become as individualistic as possible—personal cars for specific trips, one person with one goal. There was a time when this wasn't so, a single place where several goals of different people converged. This idea, so simple yet powerful, is what the film is based on. A simpler time, in which the connections you make with the people accompanying you on the journey make it something unique, valuable, and unrepeatable.

To begin with, the stagecoach itself can be interpreted as an allegory, representing American expansion, where settlers defy the elements and external adversities to expand “civilization” into remote territories. Inside this stagecoach, a small “community” is formed, made up of people of all types, with different interests, tastes, and backgrounds, but a common destination: Lordsburg. This addresses one of Ford's most recurring themes: communities and how they function. In a community, everyone seeks happiness (Lordsburg), and this can be achieved through coexistence among its members.

Throughout the trip, the film explores how social pressure influences people's behavior. An example is Lucy Mallory, who starts out rejecting Dallas. As the trip progresses, she ends up sympathizing with her due to her kind and selfless attitude. But when they finally arrive in Lordsburg and Lucy reunites with the bulk of society, society exerts its pressure on her and she becomes cold toward Dallas again. Showing, in this way, a society with a pulse, capable of controlling the individual conduct of the characters—a surprisingly modern theme.

This theme of alienation also appears in a scene I especially like: when, at the end, Luke Plummer gets violent out of fear of Ringo Kid, and in the bar, they hide the mirror for fear that Luke will break it. It’s an iconic moment that can be seen as a mere comic device, but it not only evidences the destruction fear can cause, it adds a deeper symbolic layer. The fact that it’s a mirror they hide gives the action depth. Fear and agitation can make people not see themselves clearly, losing their identity and acting in a way that doesn't represent them, just as the previously mentioned social pressure can do.

Socially, one can also observe the power relations between characters. Very visible between Buck and Curly Wilcox, especially in the vote where Curly puts his vote before Buck's, or between Curly and Ringo (police – prisoner), Dallas and Ringo (beloved – lover), or Josiah and Peacock (submissive dealer – determined consumer). It shows the biggest problem of communities: in them, everyone never wins; there are always some who sacrifice their interests for the good of the rest. This isn't a movie invention; it is real and observed continually in life. Life in a community isn't perfect, but it is easier than an individualistic life.

<blockquote>“I guess you can’t break outta prison and into society in the same week.” – Ringo Kid</blockquote>

Associated with this last point are the social classes represented. Generally, the most marginal and controversial characters of society (with the worst reputation) are the ones who show the most robust moral values, evidencing a repulsive cultural hypocrisy still present in our society, where what one represents carries more weight than what one does. The clearest example is Gatewood, whose profession as a banker makes him respected by all, but at the same time, he is stealing and trying to flee the consequences. To top it off, he is selfish, a coward, and a whiner, yet he doesn't receive the same condescending reactions with which Ringo or Dallas are treated, whose attitude is much more humble and respectful. This is one of the reasons this movie triumphed and revived the western genre. It goes beyond created archetypes and endows the characters with depth. A depth detached from their typical and predictable behaviors on which westerns made at that time were based, a depth that surpasses entertainment to show real problems. As I said, the characters don't do what they "should": The banker isn't honest, the doctor isn't serious, the outlaw isn't evil, the prostitute isn't lustful or immoral... Like onions or like Shrek, they have layers.

If we dig deep enough, we can observe that almost no character is free of prejudice. From the Navajo Indian at the beginning who betrays the Apaches out of resentment toward them, to Curly Wilcox who feels challenged by the cavalry at the start when they insinuate he fears the Indians. Each character is unique and has their own perspective, with flaws and virtues inherent to human beings.

On the other hand, there is the landscape: Monument Valley on the Arizona/Utah border. It is no coincidence that <i>Stagecoach</i> is the first movie to use this landscape as a backdrop, the first of many. A barren desert unaltered by the passage of time and filled with beauty. This beauty can awaken questions like whether we really belong in this place—do we fit into such a beautiful plain or are we forcing our way through? Are we impure beings in a pure place? This landscape can evoke the primitive, the wild, the rediscovery of beauty in the forgotten, the danger in the unknown. One of the keys that makes the landscape convey so much is the gigantic mountain formations (inselbergs) characteristic of Monument Valley, which suggest that nothing is eternal, that time passes, thus reminding us of the ephemeral nature of life. They are structures that, like the stars or the sea, have been there for millennia and will take millions of years to disappear. In a whole lifetime, there is no time to appreciate the change in them. In this way, these prehistoric rock pillars highlight the insignificance of man, both spatially and temporally.

<blockquote>"And remember this: What's good for the banks it's good for the country" – Gatewood</blockquote>

Following this same theme, the contrasts between the open desert and the claustrophobic stagecoach are notable, suggesting an incongruity between the available space and the space they are forced to share. This ties in with the society section: it can refer to how we create urban nuclei in reduced spaces or mold the environment to our will wherever we go. Furthermore, the interior scenes in this movie were filmed in covered sets, something not usually done at that time, which helps increase the aforementioned claustrophobic sensation. These contrasts might insinuate that life in cities is false, precarious, and stifling, while in nature one finds true freedom, abundance, and connection with oneself, linking to the happy ending of the film, in which the heroes head toward free and harmonious nature.

As individuals, we depend entirely on our context. A context full of immaterial and physical inventions created by other previous humans. In the movie, there is interaction by the protagonists with these inventions: the law, "democratic" voting, social prejudices, greed, the stagecoach, banks, the telegraph, revolvers, the cavalry... We build our lives on existing inventions created to make us less miserable: unfortunately, they are inexact inventions subject to failure. Some crook banker will steal, some bandits will kill and go unpunished accusing another person, some prostitute victim of her circumstances will be viewed with pity by the rest and will believe herself incapable of achieving a better future, even some doctor who has been able to give and save lives will be expelled from his town for debts. Thank God this is classic cinema; the good guys win and the bad guys lose, but the idea is there.

Classic cinema is so cool because it usually gives the viewer what they want: in an era when tragic endings didn't usually have such a good reception and when Hollywood governed the noble art of cinema, there was a peak in the creation of films with a predictable but gratifying narrative style that simply worked. What makes this movie so special is that it is continuously criticizing a value system that was new at the time and ironically corrupted by the passage of time, all while creating a coherent, interesting, and well-rounded world.

Alongside spatial contrasts are sociological contrasts. The two protagonist couples Lucy/Hatfield and Dallas/Ringo are opposites. On one hand, we have a love inhibited by the obtuse influence of civilized society, and on the other, a more sincere love without filters or prejudices which, although Dallas doesn't quite believe it, is there. The repugnance John Ford feels toward social conventions is palpable in every instant of his work. Another curious contrast is Hatfield/Gatewood, whose professions oppose each other, showing the gambler whose gain is based on constant chance and the banker, which requires—generally—luck at birth. Continuing with contrasts, one I really like is Ringo/Dallas: Ringo stays in the stagecoach to end the lives of the Plummers, while Dallas stays to finish "giving life" to Lucy's baby. This fact becomes notable when the two are about to flee right after the baby is born, but Dallas wants to stay to finish caring for the baby as long as she can, and Ringo stays too upon noticing there might be Indians (they don't flee "their destiny"). In fact, the dialogue Ringo and Dallas share at this point is very good and the power of Dallas over Ringo is observed, since he starts by asking her to go to the cabin alone and wait for him while he finishes off the Plummers, but finally Dallas convinces him to go and let her stay caring for the child (she turns the situation around), but just before leaving he sees the signals of the Indians and decides to stay. The interests of giving life and giving death of each are illustrated very well. With this concept in mind, in the end, when they leave toward the horizon in the stagecoach headed to start a new life after killing the Plummers and saving the baby, it perfectly illustrates that endings are just new beginnings. That life and death go hand in hand since where something dies, another thing is born; that nothing is black or white, everything is gray. It is a perfect ending.

<blockquote>"Like an angel in a jungle." – Hatfield</blockquote>

Sometimes, the things we experience remain submerged in our minds, waiting to be unearthed in the future. I remember the first time I saw a magpie; its beauty and elegance impressed me, and I mentioned it to my mother. She told me they were "bad" animals, as they ate the eggs and young of other birds. Lately, when I see a magpie, I remember Hatfield, an elegant being stained by his actions; a villain with heroic traces. From the way he dresses—black jacket, linked to evil and selfishness, with a white hat, associated with goodness and transparency—passing through his polite and certainly respectful behavior, but full of prejudices—many inherent to a Southern mentality—which, on occasions, prevent him from seeing things clearly, to his way of earning a living: gambler, an obtuse profession where luck determines the winner. All of this shows us the incoherent duality proper to the character. There are some interesting details surrounding the character: on one hand his names, Hatfield and Greenfield, which can be seen as premonitions of Ringo's future: throwing himself on the ground to defeat the Plummers (Hatfield: Hat-field) and the house in the country he goes to with Dallas at the end (Greenfield: Green-field). This gives a premonitory and mystical air to his persona. On the other hand, there is his relationship with cards, specifically the black eight. At the moment of the child's birth, before his death, he is playing solitaire and Buck remarks that he is holding a black eight; another black eight is shown in Luke Plummer's hands prior to his death. In many cultures, the eight is related to the connection between physical and spiritual forces due to its shape resembling infinity, suggesting that death is not really the end, that there is something imperishable within us. Putting both concepts together, there is an interesting idea being put on the table, but it leaves many more questions than answers. Given that everything I write here can be seen as philosophical speculation and this is a movie review, I will opt for the void, a contradictory void, which upon being written, transforms into something, an impossible and blurry something, but necessary.

Another emblematic character is Peacock, whom everyone confuses with a parson but who, ironically, is a traveling liquor salesman. The irony is huge: both characters distribute happiness but normally to radically different people (alcoholics or religious people). This irony, put in context, is even heavier because: Prohibition was instituted mainly by very conservative people (mostly religious), who considered alcohol the fruit of several social evils. So to speak, he is a "wolf in sheep's clothing." To top it off, nobody remembers his name or his place of origin, nobody pays attention to him, exactly the opposite of how a parson transmitting the "word of God" on Earth—whose teachings are usually important—would be treated. This ties in with characters transcending their archetypal behavior and creates a very cool thematic gag.

<blockquote>“There are some things a man just can’t run away from.” – Ringo Kid</blockquote>

There is also the damn John Wayne, an actor who, at that time, was practically unknown (although he had already participated in 80 movies) with whom Ford became infatuated and whose participation constituted the start of a prolific career, creating a name that went down in Hollywood history. Wayne, who was 31 years old, had already participated as an extra in some of Ford's movies, but this was his first leading role. This actor is characterized by his naturalistic acting with a sober and contained style that can seem cocky. They did well making this his first leading role, since with this style of acting it is convenient that there are no very juvenile features in his face. In this way, his interpretation results more credible.

Wayne creates an ideal of a male protagonist, of few words, but who carries a weapon and knows how to use it. Ironically, he is the only “innocent” character whose eyes ignore social prejudices. The characteristic zoom to his face is an unforgettable way to introduce a hero. The <i>Deus ex machina</i> at the end (3v1 ez noobs) is an almost dreamlike but optimistic happy ending that conveys to us that, despite what it may seem, life doesn't have to be unfair; injustice disappears to give way to an uncertain but hopeful future. Injustice disappears when the law is broken, thanks to the marshal allowing Ringo Kid to face his enemies and leave with his romantic interest. With the victory in the shootout, Ringo not only manages to move forward, he also manages to get out of society. To go to a remote place, where he can live off the land with his partner and transcend the arbitrary divisions of society. One of the greatest possible trophies in the imaginary of westerns.

The cinematography and the play of shadows also speak for themselves. Visually, Ford had a talent for aiming the camera at the center of the soul and hitting the bullseye. Creating fleeting but sticky images that remain permanently impregnated in our iris and chase us in dreams: That shadow of Dallas in the doorway, the zoom to Ringo, 3 gigantic rocky pillars stalking the stagecoach...

<blockquote>“What did you get?”
“Only the first word, sir.”
“Gerónimo”</blockquote>

Regarding criticisms of the movie for being racist and not portraying Native Americans well: Despite its representation of Indians as one-dimensional, simple, and savage villains, the movie is telling us on a deeper level that “civilized” society is perhaps not as civilized and fair as we believe. That perhaps we are the savages and not them. We pile up in small areas and build cities while they enjoy the freedom of the natural landscape living a nomadic life. We have as a base a system that hangs by a thread and can crumble giving rise to poverty (Gatewood) or crime (the Plummers). We distance ourselves from our families for jobs (Lucy's husband). We create a committee (Law and Order League) that expels citizens (Dallas and Josiah) from their homeland. While they live in more primitive and simple ways, in greater tune with our authentic nature. Furthermore, Dallas and Ringo at the end leave in search of a lifestyle outside of society, similar to that of the indigenous people. That is why I think that, while they are portrayed in a caricatured way, the movie is not against them. Another reason supporting this line of thought is that John Ford had one of the most impressive action scenes recorded to date in his film (the confrontation scene with Indians) and instead of placing it as the grand final climax, he uses it to give way to the true denouement against the Plummer brothers (Americans who live in society and abuse its imperfection).

As a fact, it is true that Ford was criticized his whole life for this representation of Indians and, ironically, his western of redemption toward them (<i>Cheyenne Autumn</i>) was a box office failure and marked the end of his career (after this, studios didn't want to finance his projects). Which leads us to think that the theme he treated in <i>The Man Who Shot Liberty Valance</i> is true: people don't want to know how what they have was really achieved; if knowing it is painful, they prefer to live in a lie.

Some fun facts surrounding the movie:

→ More names with references include the banker Mr. Gate-wood, which can be interpreted as putting doors to the mountain/forest (houses), an action often managed by banking. The name Dallas comes from Old English and means "valley house," like the one she heads to with Ringo at the end of the film; finally, the name Ringo means rings in English, symbolizing the union he creates with Dallas.

→ Another detail is that in several shots, mainly after Ringo Kid's interactions talking about the 3 Plummer brothers, symbols appear on screen representing them, such as a cactus with 3 heads or 3 inselbergs in the desert.

→ The hat John Wayne wears in the movie was bought by him personally and he continued using it in some movies for the next 20 years until in 1959 he left it in a display case in his house due to its poor condition. <a href="https://x.com/Nitrotoluen0/status/1624399732931022851">tweet</a>

→ In the chase with the Indians, the horses were going at 65-67km/h. Ford said it, although God knows he was a bit of a lying rascal.

→ For the stagecoach scene, Ford hired 200 authentic Navajo Indians and paid them a union wage; this earned Ford their respect and the name “Natani Nez” or Tall Leader.

→ Geronimo was the only Indian who was actually Apache (outside the role), the rest were Navajos.

A slightly more personal note is that on days when I struggle to sleep, for some reason I start thinking about this movie. In fact, a good part of this review has been written under these circumstances. It has something that imprinted on my mind and made me unable to stop turning it over, and the more I thought about it, the better it seemed to me. I know it's not for everyone, but seeing what a movie that came out 63 years before I was born has contributed to me makes me reflect. It gives meaning to everything. The actors are dead but a small part of their life remained impregnated in the film and we can watch it, enjoy it, and make it part of us. It is something I find beautiful and one of the reasons I like old movies.

<blockquote>"I've brought hundreds of those little fellas into the world and the new one was always the prettiest"– Doc Boone</blockquote>

Summarizing, many themes are touched upon, but if I have to choose one, let it be birth. One of the multiple definitions of birth is: “Act of starting to be” and, in this context, many things are born: bonds between characters, Lucy's son, justice toward the corrupt. I have always thought that time was the most important thing one had in life. This movie highlights that time is just a resource we have to do things and what is important are the things we do, the actions that are born from us: the bonds we create with people, the initiatives we carry forward, and the questions we ask ourselves. Because the difference between existing and living lies in acting. What would become of this movie if Ringo hadn't escaped from jail, hadn't taken control of the stagecoach, hadn't challenged the Plummer brothers, or didn't propose to Dallas to go with him to his cabin? Exactly, it would be absolutely NOTHING. Because we are not what we represent nor what we seem, we are what we do.
`