export default `
<blockquote>"Well, they're saved from the blessings of civilization." – Doc Boone</blockquote>

Pocas películas en mi vida he visto que tengan un ritmo remotamente similar al que tiene esta joya. No contenta con esto, es la primera <i>road movie</i> (bien hecha) de la historia. Y por si fuera poco, Orson Welles la vio más de 40 veces para hacer <i>Ciudadano Kane</i>. Cuando, en el 67, le preguntaron en una entrevista por los directores que admiraba, mencionó por encima de TODO a los "viejos maestros", entendiendo por estos a John Ford, John Ford y John Ford.

Publicada en 1939. Los años 30 en Estados Unidos estuvieron marcados por la Gran Depresión (iniciada por el crack del 29), el desastre del Dust Bowl (agricultores tristes), el fin de la ley seca en el 33, tensión por la llegada de la Segunda Guerra mundial y varios huracanes fuertes que azotaron Florida y Nueva Inglaterra. Siendo un periodo de tanta pobreza e inestabilidad, había un gran descontento político por la forma de afrontar la crisis, además de con la banca y la Bolsa de Valores. Se crearon varios sindicatos que buscaban pelear por los derechos de los trabajadores. Por las consecuencias del Dust Bowl cientos de campesinos del suroeste se vieron obligados a trasladarse a California para poder trabajar, haciendo un viaje similar al que se someten los protagonistas de la película, en el que, en vez de enfrentarse a los indios, se enfrentaban a los prejuicios de la gente, que en ocasiones, pueden ser peores que las flechas de los nativos.

Primero de todo voy a hacer un breve resumen de lo que ocurre, si la acabaís de ver y no quieres repasarlo salta hasta la línea de guiones (-). 

Se sitúa en los años 1880 en Tonto, un pueblecillo en Arizona, EEUU. 8 variopintos viajantes se ven volcados en un variado viaje que balizará el vestigio de sus vidas. Todos se dirigen a Lordsburg, Nuevo México, cada uno por motivos diversos:

- Lucy Mallory: Una mujer embarazada en busca de su marido soldado;
- Hatfield: un jugador, veterano de guerra, que al ver a Lucy se une a la travesía como una polilla a la luz;
- Gatewood: un banquero que huye del pueblo robando un depósito recién recibido y abandonando a su mujer;
- Curly Wilcox: el mariscal que viaja, en parte, para velar por la seguridad de los pasajeros ante una amenaza apache en el viaje, y también para encontrar a Ringo Kid y cobrar su recompensa, hablando de este;
- Ringo Kid: Un fugitivo de la justicia que busca a los hombres que mataron a su familia y lo metieron en la cárcel;
- Dallas: una prostituta desterrada de su pueblo por la Liga de la Ley y el Orden, una organización que se formó después de la Guerra Civil para velar por los "valores morales correctos" <a href="https://www.newyorkalmanack.com/2021/10/saratoga-countys-law-and-order-league/"> (más info aquí, solo curiosos) </a>;
- Buck: el cobarde pero amigable conductor de la diligencia;
- Peacock: un vendedor ambulante de licor al que todo el mundo confunde con un pastor y, para rematar;
- Josiah Boone: el doctor nihilista, también expulsado del pueblo, en este caso, por sus deudas y su mala reputación.

Como he mencionado, son un grupo muy diverso, por lo que, en condiciones normales, la mayoría de estos individuos no interactuaría entre ellos. Pero este no es el caso. Como ya he dicho, son los años 1880 y la única forma que tienen de transportarse es un claustrofóbico aparato llamado diligencia.
¡Qué agobio!
No solo se observa lo mucho que ha cambiado el mundo respecto al transporte, sino que se palpa por qué ha cambiado tanto. A pesar de que estamos destinados a vivir esta vida y lo único que podemos elegir es la bondad con la que tratamos a los que nos rodean, a veces, por puro egoísmo o inercia, no somos conscientes de que el resto de las personas son como nosotros.

Voy a ir directamente al final de la trama, sin detenerme en las vicisitudes intermedias:

- Lucy: con un hijo y junto a su marido;
- Hatfield: muerto a manos de los apaches;
- Gatewood: encarcelado por su fechoría;
- Curly Wilcox: libera a Ringo de la ley renunciando a la recompensa por capturarlo;
- Ringo Kid y Dallas: huyen juntos de la civilización;
- Buck: termina el tiroteo herido pero sano y salvo;
- Peacock: vuelve a su casa con una gran historia que contar a su familia;
- Josiah Boone: en cuanto a motivos, es el único que empieza igual que acaba no aprende nada, porque ya sabe lo que hay. Tal vez gana una historia y hace lo único que sabe que es correcto: ayudar al resto, porque a sí mismo no se puede ayudar. Qué ironía que el personaje más cínico sea el doctor que ayuda a curar a la gente. La peli está llena de estas sátiras, es uno de los motivos por los que me gusta tanto.

-----------------------------------------------------------------------

Con el paso del tiempo, el transporte ha ido haciéndose lo más individualista posible, coches personales para hacer viajes concretos, una persona con un objetivo. Hubo un tiempo en el que esto no era así, un mismo lugar en el que convergían varios objetivos de distintas personas. Esta idea tan simple pero potente es en la que se basa la cinta. Un tiempo más sencillo, en el que las conexiones que haces con las personas que te acompañan en el viaje hacen de este algo único, valioso e irrepetible.

Para comenzar, la propia diligencia puede interpretarse como una alegoría, al representar la expansión americana, donde los colonos desafían los elementos y las adversidades externas para ampliar la “civilización” hacia territorios remotos. Dentro de esta diligencia se forma una pequeña “comunidad” constituida por gente de todo tipo, con intereses, gustos y trasfondos diferentes, pero un destino común: Lordsburg. Así se aborda uno de los temas más recurrentes de Ford: las comunidades y su funcionamiento. En una comunidad todos buscan la felicidad (Lordsburg), y esta puede lograrse con la convivencia entre sus integrantes.

A lo largo del viaje, se explora cómo la presión social influye en el comportamiento de las personas. Como ejemplo está Lucy Mallory, que comienza rechazando a Dallas. A medida que el viaje avanza, termina simpatizando con ella por su actitud amable y desinteresada. Pero cuando al final llegan a Lordsburg y Lucy se reencuentra con el grueso de la sociedad, esta ejerce su presión sobre ella y vuelve a ser fría con Dallas. Mostrando, de este modo, una sociedad con pulso, capaz de controlar la conducta individual de los personajes, un tema sorprendentemente moderno.

Este tema de alienación también aparece en una escena que me gusta especialmente: cuando, al final, Luke Plummer se pone violento por miedo a Ringo Kid, y en el bar ocultan el espejo por temor a que Luke lo rompa. Es un momento icónico que puede ser visto como un mero recurso cómico, pero que no solo evidencia la destrucción que puede causar el miedo, sino que añade una capa simbólica más profunda. Que sea un espejo lo que esconden dota a la acción de profundidad. El miedo y la agitación pueden hacer que las personas no se vean a sí mismas con claridad, perdiendo su identidad y actuando de una forma que no les representa, tal y como puede hacer la presión social previamente mencionada.

Socialmente, también se pueden observar las relaciones de poder entre los personajes. Muy visibles entre Buck y Curly Wilcox, especialmente en la votación en la que Curly antepone su voto al de Buck, o entre Curly y Ringo (policía – preso), Dallas y Ringo (amada – amante) o Josiah y Peacock (traficante sumiso – consumidor determinado). Se muestra el mayor problema de las comunidades: en ellas nunca ganan todos, siempre hay algunos que sacrifican sus intereses por el bien del resto. Esto no es un invento del cine, es real y en la vida se observa continuamente. La vida en comunidad no es perfecta, pero es más fácil que una vida individualista.

<blockquote> “I guess you can’t break outta prison and into society in the same week.” – Ringo Kid</blockquote>

Asociadas a esto último, están las clases sociales representadas. Generalmente, los personajes más marginales y controvertidos de la sociedad (con peor reputación), son quienes muestran unos valores morales más robustos, evidenciando una hipocresía cultural repulsiva todavía presente en nuestra sociedad, donde pesa más lo que se representa que lo que se hace. El ejemplo más claro es Gatewood, cuyo oficio de banquero le hace ser respetado por todos, pero a su vez está robando e intentando huir de las consecuencias. Para rematar es egoísta, un cobarde y un quejica, pero no recibe las mismas reacciones de condescendencia con la que se trata a Ringo o Dallas cuya actitud es mucho más humilde y respetuosa. Este es uno de los motivos por los que esta película triunfó y revivió el género western. En ella se va más allá de los arquetipos creados y se dota a los personajes de profundidad. Una profundidad desligada de sus comportamientos típicos y predecibles en los que se basaban los westerns que se hacían por ese entonces, una profundidad que sobrepasa el entretenimiento para mostrar problemas reales. Como bien he dicho los personajes no hacen lo que "deberían": El banquero no es honrado, el médico no es serio, el forajido no es malvado, la prostituta no es lujuriosa ni inmoral... Como las cebollas o como Shrek, Tienen capas.

Si ahondamos lo suficientemente hondo podemos observar que casi ningún personaje está libre de prejuicios. Desde el indio navajo del principio que delata a los apaches por rencor hacia ellos, hasta Curly Wilcox que se siente retado por la caballería al inicio cuando insinúan que teme a los indios. Cada personaje es único y tiene su propia perspectiva, con fallos y virtudes inherentes al ser humano.

Por otro lado, está el paisaje: el Monument Valley en la frontera Arizona/Utah. No es coincidencia que <i>La Diligencia</i> sea la primera película en utilizar este paisaje como fondo, la primera de muchas. Un yermo desierto inalterado por el paso del tiempo y colmado de belleza. Esta belleza puede despertar preguntas como si realmente pertenecemos a este lugar, ¿Encajamos en una llanura tan hermosa o nos estamos abriendo paso a pura fuerza? ¿Somos seres impuros en un lugar puro? Este paisaje puede evocar lo primitivo, lo salvaje, el redescubrimiento de la belleza en lo olvidado, el peligro en lo desconocido. Una de las claves que hacen que el paisaje transmita tanto son las gigantescas formaciones montañosas (inselbergs) características del Monument Valley, que sugieren que nada es eterno, que el tiempo pasa, recordándonos así lo efímero de la vida. Son estructuras que, como las estrellas o el mar, llevan ahí milenios y tardarán millones de años en desaparecer. En una vida entera no hay tiempo para apreciar el cambio en ellas. De este modo, estos prehistóricos pilares de roca resaltan la insignificancia del hombre, tanto espacial como temporalmente.

<blockquote>"And remember this: What's good for the banks it's good for the country" – Gatewood</blockquote>

Siguiendo este mismo tema, son destacables los contrastes entre el despejado desierto y la claustrofóbica diligencia, que sugieren una incongruencia entre el espacio disponible y el que se ven obligados a compartir. Esto hila con el apartado de la sociedad: puede hacer referencia a como creamos núcleos urbanos en espacios reducidos o moldeamos el entorno a nuestra voluntad allá donde vamos. Además, las escenas de interiores en esta película fueron grabadas en lugares cubiertos, cosa que no se solía hacer por aquella época y que ayuda a incrementar la sensación claustrofóbica mencionada. Estos contrastes pueden insinuar que la vida en las ciudades es falsa, precaria y agobiante, mientras que en la naturaleza se encuentra la verdadera libertad, abundancia y conexión con uno mismo, hilando así con el final feliz de la película, en el que los héroes se dirigen hacia la libre y armónica naturaleza.

Como individuos dependemos enteramente de nuestro contexto. Un contexto lleno de invenciones inmateriales como físicas creadas por otros humanos previos. En la película hay interacción de los protagonistas con estas invenciones: la ley, las votaciones "democráticas", los prejuicios sociales, la codicia, la diligencia, los bancos, el telégrafo, los revólveres, la caballería... Construimos nuestra vida sobre invenciones existentes que se crearon para hacernos menos miserables: por desgracia son invenciones inexactas y sujetas al fallo: algún banquero chorizo robará, algunos bandidos matarán y se irán impunes acusando a otra persona, alguna prostituta víctima de sus circunstancias será vista con pena por el resto y se creerá incapaz de conseguir un mejor futuro, inclusive algún doctor que ha podido dar y salvar vidas será expulsado de su pueblo por deudas. Gracias a Dios, esto es cine clásico, los buenos ganan y los malos pierden, pero la idea está ahí.

El cine clásico es tan guay porque acostumbra a dar lo que quiere el espectador: en una época en la que los finales trágicos no habituaban a tener tan buen recibimiento y en la que Hollywood gobernaba el noble arte del cine, hubo un apogeo en la creación de cintas con un estilo narrativo predecible pero gratificante, que, simplemente funcinaba. Lo que hace tan especial a esta película es que está contínuamente criticando un sistema de valores por aquél entonces nuevo e irónicamente corrompido por el paso del tiempo, todo esto mientras crea un mundo coherente, interesante y redondo.

Junto a los contrastes espaciales están los contrastes sociológicos. Las dos parejas protagónicas Lucy/Hatfield y Dallas/Ringo son opuestas. Por un lado, tenemos un amor cohibido por la obtusa influencia de la sociedad civilizada y por otro, un amor más sincero y sin tapujos ni prejuicios que, aunque Dallas no se lo termina de creer, está ahí. La repugnancia que siente John Ford hacia las convenciones sociales es palpable en cada instante de su obra. Otro contraste curioso es el de Hatfield/Gatewood, cuyos oficios se contraponen mostrando al jugador cuya ganancia se basa en el azar constante y, el banquero, que requiere —por lo general— suerte en el nacimiento. Continuando con los contrastes, uno que me gusta mucho es el de Ringo/Dallas: Ringo se queda en la diligencia para terminar con la vida de los Plummer, mientras que Dallas se queda para terminar de "dar vida" al bebé de Lucy. Este dato se hace notable cuando los dos están a punto de huir justo después de que nazca el bebé pero Dallas se quiere quedar para terminar de cuidar al bebé el tiempo que pueda y Ringo se queda también al notar que puede haber indios (no huyen de "su destino"). De hecho, el diálogo que comparten Ringo y Dallas en este punto es muy bueno y se observa el poder de Dallas sobre Ringo, ya que este le comienza pidiendo que se vaya a la cabaña sola y le espere mientras él acaba con los Plummer pero finalmente Dallas le convence para que se vaya él y ella se quede cuidando al niño (le da la vuelta a la situación) pero justo antes de partir ve las señales de los indios y decide quedarse. Se ilustran muy bien los intereses de dar vida y dar muerte de cada uno. Con este concepto en mente, en el final, cuando parten hacia el horizonte en la diligencia encaminados a comenzar una nueva vida después de dar muerte a los Plummer y salvar al bebé se ilustra perfectamente que los finales son solo nuevos comienzos. Que la vida y la muerte van de la mano ya que donde muere algo, nace otra cosa, que nada es blanco o negro, todo es gris. Es un final perfecto.

<blockquote>"Like an angel in a jungle." – Hatfield</blockquote>

A veces, las cosas que vivimos quedan sumergidas en nuestra mente, esperando a ser, en un futuro, desenterradas. Recuerdo la primera vez que vi una urraca, su belleza y elegancia me impresionaron, se lo comenté a mi madre. Ella me dijo que eran animales "malos", ya que se comían los huevos y las crías de otras aves. Últimamente, cuando veo una urraca recuerdo a Hatfield, un ser elegante manchado por sus acciones; un villano con resquicios heroicos. Desde la forma de vestir —chaqueta negra, vinculados a la maldad y el egoísmo, con sombrero blanco, asociado a la bondad y transparencia—, pasando por su comportamiento educado y ciertamente respetuoso, pero colmado de prejuicios —muchos inherentes a una mentalidad sureña— que, en ocasiones, le impiden ver las cosas con claridad, hasta su forma de ganarse la vida: jugador, un oficio obtuso en el que la suerte determina al ganador. Todo ello nos muestra la dualidad incoherente propia del personaje. Hay algunos detalles interesantes que rodean al personaje: por un lado sus nombres, Hatfield y Greenfield, que pueden verse como premoniciones del futuro de Ringo: tirándose al suelo para derrotar a los Plummer (Hatfield: Sombrero-campo) y la casa en el campo a la que va con Dallas al final (Greenfield: Verde-campo). Esto otorga un aire premonitorio y místico a su persona. Por otro lado, está su relación con las cartas, concretamente el ocho negro. En el momento del nacimiento del niño, antes de su muerte, está jugando al solitario y Buck remarca que este tiene en mano un ocho negro, otro ocho negro es mostrado en las manos de Luke Plummer de forma previa a su muerte. En muchas culturas, el ocho está relacionado a la conexión entre las fuerzas físicas y las espirituales por su forma semejante al infinito, sugiriendo que la muerte realmente no es el final, que hay algo imperecedero dentro de nosotros. Juntando ambos conceptos, hay una idea interesante que se está poniendo sobre la mesa, pero que deja muchas más preguntas que respuestas. Dado que todo lo que escriba aquí puede ser visto como especulación filosófica y esto es una review de una peli, optaré por el vacío, un vacío contradictorio, que al quedar escrito, se transforma en algo, un algo imposible y borroso, pero necesario.

Otro personaje emblemático es Peacock, a quien todos confunden con un párroco pero que, irónicamente, es un vendedor de licor ambulante. La ironía es enorme: ambos personajes reparten felicidad pero, normalmente a personas radicalmente diferentes (alcohólicos o religiosos). Esta ironía, puesta en contexto es todavía más tocha porque: la Ley Seca fue instaurada principalmente por gente muy conservadora (religiosos en su mayor parte), que consideraba que el alcohol era fruto de varios males sociales. Por así decirlo, es un "lobo con piel de cordero". Para colmo nadie recuerda su nombre ni su lugar de origen, nadie le hace caso, justo al contrario cómo se trataría a un párroco que transmite la "palabra de Dios" en la Tierra cuyas enseñanzas suelen ser importantes. Esto liga con los personajes trascendiendo su comportamiento arquetípico y crea un gag temático muy chulo.

<blockquote> “There are some things a man just can’t run away from.” – Ringo Kid</blockquote>

También está el maldito John Wayne, un actor que, por aquel entonces, era prácticamente desconocido (aunque ya había participado en 80 películas) con quien Ford se encaprichó y cuya participación constituyó el inicio de una carrera prolífica, creando un nombre que pasó a la historia de Hollywood. Wayne, que tenía 31 años, ya había participado como extra en algunas películas de Ford, pero este fue su primer papel protagónico. Este actor se caracteriza por su actuación naturalista con un estilo sobrio y contenido que puede parecer chulesco. Hicieron bien en que este fuera su primer papel protagónico, ya que, con este estilo de actuación conviene que no haya rasgos muy juveniles en su rostro. De este modo, resulta más creíble su interpretación.

Wayne crea un ideal de protagonista masculino, de pocas palabras, pero que lleva un arma y sabe usarla. Irónicamente, es el único personaje “inocente” cuyos ojos ignoran los prejuicios sociales. El zoom a su cara característico es una inolvidable forma de presentar a un héroe. El Deus ex machina del final (3v1 ez noobs) es un final feliz casi onírico pero optimista y que nos transmite que, a pesar de lo que pueda parecer, la vida no tiene por qué ser injusta, la injusticia desaparece para dar lugar a un futuro incierto pero esperanzador. La injusticia desaparece al romperse la ley, gracias a que el mariscal permite que Ringo Kid se enfrente a sus enemigos y que se marche con su interés romántico. Con la victoria en el tiroteo, Ringo no solo consigue salir adelante, también consigue salir de la sociedad. Irse a un lugar alejado, donde vivir de la tierra con su pareja y trascender las arbitrarias divisiones de la sociedad. Uno de los mayores trofeos posibles en el imaginario de los westerns.

La fotografía y los juegos de sombras también hablan por sí solos. Visualmente Ford tenía talento para apuntar la cámara al centro del alma y dar de lleno. Creando imágenes fugaces pero pegajosas que se quedan impregnadas de forma permanente en nuestro iris y nos persiguen en sueños: Esa sombra de Dallas en la puerta, el zoom a Ringo, 3 gigantescos pilares rocosos acechando la diligencia...

<blockquote>“What did you get?”
“Only the first word, sir.”
“Gerónimo”</blockquote>

En lo referente a las críticas de la película por ser racista y no retratar bien a los nativos americanos. Pese a su representación de los indios como unos villanos unidimensionales, simples y salvajes, la película nos está diciendo a un nivel más profundo que la sociedad “civilizada” tal vez no es tan civilizada y justa como creemos. Que tal vez los salvajes seamos nosotros y no ellos. Nosotros nos apilamos en zonas pequeñas y construimos ciudades mientras que ellos disfrutan de la libertad del paisaje natural viviendo una vida nómada. Nosotros tenemos como base un sistema que pende de un hilo y se puede desmoronar dando lugar a pobreza (Gatewood) o delincuencia (los Plummer). Nosotros nos alejamos de nuestras familias por los oficios (marido de Lucy). Nosotros creamos un comité (Liga de la Ley y el Orden) que expulsa a ciudadanos (Dallas y Josiah) de su tierra de origen. Mientras que ellos viven de formas más primitivas y sencillas, en mayor sintonía con nuestra auténtica naturaleza. Además, Dallas y Ringo al final parten en busca de un estilo de vida fuera de la sociedad, similar al de los indígenas. Por ello pienso que, si bien son retratados de forma caricaturesca, la película no está en su contra. Otro motivo que apoya esta línea de pensamiento es que John Ford tenía una de las escenas de acción más impresionantes grabadas hasta la fecha en su cinta (la escena de enfrentamiento con indios) y en vez de ponerla como el gran clímax final, la usa para dar paso al verdadero desenlace contra los hermanos Plummer (americanos que viven en sociedad y abusan de su imperfección). 

Como dato, es cierto que Ford durante toda su vida fue criticado por esta representación de los indios e, irónicamente su western de redención hacia ellos (Cheyenne Autumn o El gran combate) fue un fracaso en taquilla y supuso el fin de su carrera (a partir de esto los estudios no querían financiar sus proyectos). Lo que nos lleva a pensar que el tema que trató en El hombre que mató a Liberty Balance es cierto, la gente no quiere saber cómo realmente se consiguió lo que tienen, si saberlo es doloroso prefieren vivir en una mentira.


Algunos funfacts que rodean la peli:

&rarr;	Más nombres con referencias son el del banquero Sr. Gate-wood, pudiendo interpretarse como poner puertas al monte (casas) acción que muchas veces gestiona la banca. El nombre de Dallas viene del inglés antiguo y significa casa del valle, como a la que se dirige con Ringo al final del filme, finalmente el nombre Ringo significa anillos en inglés, simbolizando la unión que este crea con Dallas. 

&rarr;	Otro detalle es que en varios planos principalmente después de interacciones de Ringo Kid hablando de los 3 hermanos Plummer aparecen en pantalla símbolos que los representan como puede ser un cactus con 3 cabezas o 3 inselbergs en el desierto.

&rarr;	El sombrero que lleva John Wayne en la película se lo compró él personalmente y lo siguió usando en algunas películas los siguientes 20 años hasta que en 1959 lo dejó en una vitrina en su casa por su mal estado. <a href="https://x.com/Nitrotoluen0/status/1624399732931022851">tweet</a>

&rarr;	En la persecución con los indios los caballos iban a 65- 67km/h. Lo dijo Ford aunque Dios sabe que era un granujilla muy mentirosin.

&rarr;	Para la escena de la diligencia Ford contrató a 200 auténticos indios Navajos y les pagó un salario sindical, esto hizo que Ford se ganara su respeto y el nombre de “Natani Nez” o líder alto. 

&rarr;	Gerónimo era el único indio que realmente era Apache (fuera del papel), el resto eran Navajos.

&rarr;	A finales de los 60 Peter Bogdanovich le hizo llegar a Ford la frase completa que dijo Orson en la entrevista: "En cuanto a directores favoritos prefiero los viejos maestros, con los que me refiero a: John Ford, John Ford y John Ford. Es un poeta y un comediante, con Ford en su máximo obtienes un toque de lo que la tierra está hecha, incluso si el guión está escrito por la madre Machree". Dias más tarde Orson Welles recibió un telegrama: "Querido Orson, gracias por el cumplido, amor madre Machree".


Un apunte un poco más personal es que los días que me cuesta dormir y no me entra el sueño, por algún motivo me pongo a pensar en esta película. De hecho buena parte de esta review ha sido escrita en estas circunstancias. Tiene algo que se plasmó en mi mente y hacía que no parara de darle vueltas y cuanto más lo pensaba mejor me parecía. Sé que no es para todo el mundo, pero viendo lo que me ha aportado una película que salió 63 años antes de que yo naciera me hace reflexionar. Le da un sentido a todo. Los actores están muertos pero una pequeña parte de su vida quedó impregnada en la cinta y podemos verla, disfrutar de ella y hacer que forme parte de nosotros. Es algo que me parece bonito y uno de los motivos por los que me gustan las pelis antiguas.

<blockquote>"I've brought hundreds of those little fellas into the world and the new one was always the prettiest"– Doc Boone</blockquote>

Resumiendo se tocan muchos temas pero si hay que elegir uno que sea el nacimiento. Una de las múltiples definiciones de nacimiento es: “Acto de empezar a ser” y, en este contexto nacen muchas cosas: lazos entre los personajes, el hijo de Lucy, justicia hacia los corruptos. Siempre he pensado que el tiempo era lo más importante que uno tenía en la vida. Esta película remarca que el tiempo es solo un recurso que tenemos para hacer cosas y lo importante son las cosas que hacemos, las acciones que nacen de nosotros: los lazos que creamos con personas, las iniciativas que sacamos adelante y las preguntas que nos hacemos. Porque la diferencia entre existir y vivir está en actuar. ¿Qué sería de esta película si Ringo no se hubiera fugado de la cárcel, no hubiera tomado el control de la diligencia, no hubiera retado a los hermanos Plummer o no propusiera a Dallas ir con él a su cabaña? Exacto, no sería absolutamente NADA. Porque no somos lo que representamos ni lo que parecemos, somos lo que hacemos.
`